<a href="https://colab.research.google.com/github/arun-arunisto/OpenCVTutorialAbel/blob/main/PandasTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

## Creating data using pandas

In [2]:
pd.DataFrame({"Name":["Arun", "Arunisto", "Abel"], "Occupation":["Developer", "Student", "Student"], "Age":[25, 27, 18]})

       Name Occupation  Age
0      Arun  Developer   25
1  Arunisto    Student   27
2      Abel    Student   18

In [3]:
pd.DataFrame({"Name":["Arun", "Arunisto", "Abel"], "Occupation":["Developer", "Student", "Student"], "Age":[25, 27, 18]}, index=["Person 1", "Person 2", "Person 3"])

              Name Occupation  Age
Person 1      Arun  Developer   25
Person 2  Arunisto    Student   27
Person 3      Abel    Student   18

In [4]:
#series
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
#review sample
pd.Series([5.0, 4.7, 4.9], index=["Rating 1", "Rating 2", "Rating 3"], name="Oppenheimer Movie")

Rating 1    5.0
Rating 2    4.7
Rating 3    4.9
Name: Oppenheimer Movie, dtype: float64

## Reading a file

In [6]:
movie_data = pd.read_csv("/content/drive/MyDrive/AbelFolder/dataset/TMDB_Movies_TV.csv")

In [7]:
#shape of the dataset
movie_data.shape

(20000, 9)

***20000 records and 9 columns***

## Indexing, Selecting and Assigning

In [8]:
movie_data

,Unnamed: 0,id,original_language,title,overview,genre,keywords,cast,crew
0,0,298618,en,The Flash,"['When', 'his', 'attempt', 'to', 'save', 'his'...","['Action', 'Adventure', 'Science Fiction']","['secret identity', 'hero', 'superhero', 'base...","['Ezra Miller', 'Sasha Calle', 'Michael Keaton...",['Andy Muschietti']
1,1,346698,en,Barbie,"['Barbie', 'and', 'Ken', 'are', 'having', 'the...","['Comedy', 'Adventure', 'Fantasy']","['feminism', 'patriarchy', 'satire', 'based on...","['Margot Robbie', 'Ryan Gosling', 'Issa Rae', ...",['Greta Gerwig']
2,2,667538,en,Transformers: Rise of the Beasts,"['When', 'a', 'new', 'threat', 'capable', 'of'...","['Action', 'Adventure', 'Science Fiction']","['peru', 'alien', 'end of the world', 'based o...","['Anthony Ramos', 'Dominique Fishback', 'Peter...",['Steven Caple Jr.']
3,3,385687,en,Fast X,"['Over', 'many', 'missions', 'and', 'against',...","['Action', 'Crime', 'Thriller']","['sequel', 'revenge', 'racing', 'family', 'cars']","['Vin Diesel', 'Michelle Rodriguez', 'Tyrese G...",['Louis Leterrier']
4,4,872585,en,Oppenheimer,"['The', 'story', 'of', 'J.', 'Robert', 'Oppenh...","['Drama', 'History']","['based on novel or book', 'husband wife relat...","['Cillian Murphy', 'Emily Blunt', 'Matt Damon'...",['Christopher Nolan']
...,...,...,...,...,...,...,...,...,...
19995,19995,610,en,Mr. Show with Bob and David,"['Mr.', 'Show', 'with', 'Bob', 'and', 'David',...",['Comedy'],"['drugs', 'sketch comedy', 'dorky']","['Bob Odenkirk', 'David Cross', 'Jill Talley',...",[]
19996,19996,103578,zh,The Twin Flower Legend,"['Hua', 'Mujin', 'grew', 'up', 'during', 'the'...",['Drama'],"['friendship', 'based on novel or book', 'roma...","['Kai Xuan', 'Mao Xiaohui', 'Jim Yu', 'Kenny K...",['Wu Jin Yuan']
19997,19997,72092,zh,Xuan-Yuan Sword: Han Cloud,"['After', 'the', 'ancient', 'Emperor', 'defeat...",['Drama'],"['china', 'romance', 'based on video game', 'x...","['Leon Zhang', 'Alan Yu Menglong', 'Guan Xiaot...","['반문걸', 'Sha Jin', 'Poon Man-kit']"
19998,19998,23600,en,This Is Love,[],[],[],"['Choi Kang-hee', 'Kim Ja-ok', 'Lee Yu-ri']",[]
19999,19999,27119,en,The Comic Strip Presents,"['The', 'Comic', 'Strip', 'is', 'a', 'group', ...",['Comedy'],"['surreal', 'parody', 'anthology']","['Rik Mayall', 'Dawn French', 'Adrian Edmondso...",[]

In [9]:
#selecting a single column
movie_data.title #json

0                               The Flash
1                                  Barbie
2        Transformers: Rise of the Beasts
3                                  Fast X
4                             Oppenheimer
                       ...
19995         Mr. Show with Bob and David
19996              The Twin Flower Legend
19997          Xuan-Yuan Sword: Han Cloud
19998                        This Is Love
19999            The Comic Strip Presents
Name: title, Length: 20000, dtype: object

In [10]:
movie_data["title"] #dict

0                               The Flash
1                                  Barbie
2        Transformers: Rise of the Beasts
3                                  Fast X
4                             Oppenheimer
                       ...
19995         Mr. Show with Bob and David
19996              The Twin Flower Legend
19997          Xuan-Yuan Sword: Han Cloud
19998                        This Is Love
19999            The Comic Strip Presents
Name: title, Length: 20000, dtype: object

In [11]:
movie_data["title"][0] #indexing

'The Flash'

In [12]:
#iloc or loc
movie_data.iloc[0]

Unnamed: 0                                                           0
id                                                              298618
original_language                                                   en
title                                                        The Flash
overview             ['When', 'his', 'attempt', 'to', 'save', 'his'...
genre                       ['Action', 'Adventure', 'Science Fiction']
keywords             ['secret identity', 'hero', 'superhero', 'base...
cast                 ['Ezra Miller', 'Sasha Calle', 'Michael Keaton...
crew                                               ['Andy Muschietti']
Name: 0, dtype: object

In [15]:
movie_data.iloc[:, 2]

0        en
1        en
2        en
3        en
4        en
         ..
19995    en
19996    zh
19997    zh
19998    en
19999    en
Name: original_language, Length: 20000, dtype: object

In [20]:
movie_data.iloc[1:3, 3]

1                              Barbie
2    Transformers: Rise of the Beasts
Name: title, dtype: object

In [21]:
movie_data.loc[0, 'title']

'The Flash'

In [25]:
movie_data[:5]

,Unnamed: 0,id,original_language,title,overview,genre,keywords,cast,crew
0,0,298618,en,The Flash,"['When', 'his', 'attempt', 'to', 'save', 'his'...","['Action', 'Adventure', 'Science Fiction']","['secret identity', 'hero', 'superhero', 'base...","['Ezra Miller', 'Sasha Calle', 'Michael Keaton...",['Andy Muschietti']
1,1,346698,en,Barbie,"['Barbie', 'and', 'Ken', 'are', 'having', 'the...","['Comedy', 'Adventure', 'Fantasy']","['feminism', 'patriarchy', 'satire', 'based on...","['Margot Robbie', 'Ryan Gosling', 'Issa Rae', ...",['Greta Gerwig']
2,2,667538,en,Transformers: Rise of the Beasts,"['When', 'a', 'new', 'threat', 'capable', 'of'...","['Action', 'Adventure', 'Science Fiction']","['peru', 'alien', 'end of the world', 'based o...","['Anthony Ramos', 'Dominique Fishback', 'Peter...",['Steven Caple Jr.']
3,3,385687,en,Fast X,"['Over', 'many', 'missions', 'and', 'against',...","['Action', 'Crime', 'Thriller']","['sequel', 'revenge', 'racing', 'family', 'cars']","['Vin Diesel', 'Michelle Rodriguez', 'Tyrese G...",['Louis Leterrier']
4,4,872585,en,Oppenheimer,"['The', 'story', 'of', 'J.', 'Robert', 'Oppenh...","['Drama', 'History']","['based on novel or book', 'husband wife relat...","['Cillian Murphy', 'Emily Blunt', 'Matt Damon'...",['Christopher Nolan']

In [26]:
#choosing multiple columns using loc
movie_data.loc[0, ["title", "overview", "genre"]]

title                                               The Flash
overview    ['When', 'his', 'attempt', 'to', 'save', 'his'...
genre              ['Action', 'Adventure', 'Science Fiction']
Name: 0, dtype: object

In [27]:
movie_data

,Unnamed: 0,id,original_language,title,overview,genre,keywords,cast,crew
0,0,298618,en,The Flash,"['When', 'his', 'attempt', 'to', 'save', 'his'...","['Action', 'Adventure', 'Science Fiction']","['secret identity', 'hero', 'superhero', 'base...","['Ezra Miller', 'Sasha Calle', 'Michael Keaton...",['Andy Muschietti']
1,1,346698,en,Barbie,"['Barbie', 'and', 'Ken', 'are', 'having', 'the...","['Comedy', 'Adventure', 'Fantasy']","['feminism', 'patriarchy', 'satire', 'based on...","['Margot Robbie', 'Ryan Gosling', 'Issa Rae', ...",['Greta Gerwig']
2,2,667538,en,Transformers: Rise of the Beasts,"['When', 'a', 'new', 'threat', 'capable', 'of'...","['Action', 'Adventure', 'Science Fiction']","['peru', 'alien', 'end of the world', 'based o...","['Anthony Ramos', 'Dominique Fishback', 'Peter...",['Steven Caple Jr.']
3,3,385687,en,Fast X,"['Over', 'many', 'missions', 'and', 'against',...","['Action', 'Crime', 'Thriller']","['sequel', 'revenge', 'racing', 'family', 'cars']","['Vin Diesel', 'Michelle Rodriguez', 'Tyrese G...",['Louis Leterrier']
4,4,872585,en,Oppenheimer,"['The', 'story', 'of', 'J.', 'Robert', 'Oppenh...","['Drama', 'History']","['based on novel or book', 'husband wife relat...","['Cillian Murphy', 'Emily Blunt', 'Matt Damon'...",['Christopher Nolan']
...,...,...,...,...,...,...,...,...,...
19995,19995,610,en,Mr. Show with Bob and David,"['Mr.', 'Show', 'with', 'Bob', 'and', 'David',...",['Comedy'],"['drugs', 'sketch comedy', 'dorky']","['Bob Odenkirk', 'David Cross', 'Jill Talley',...",[]
19996,19996,103578,zh,The Twin Flower Legend,"['Hua', 'Mujin', 'grew', 'up', 'during', 'the'...",['Drama'],"['friendship', 'based on novel or book', 'roma...","['Kai Xuan', 'Mao Xiaohui', 'Jim Yu', 'Kenny K...",['Wu Jin Yuan']
19997,19997,72092,zh,Xuan-Yuan Sword: Han Cloud,"['After', 'the', 'ancient', 'Emperor', 'defeat...",['Drama'],"['china', 'romance', 'based on video game', 'x...","['Leon Zhang', 'Alan Yu Menglong', 'Guan Xiaot...","['반문걸', 'Sha Jin', 'Poon Man-kit']"
19998,19998,23600,en,This Is Love,[],[],[],"['Choi Kang-hee', 'Kim Ja-ok', 'Lee Yu-ri']",[]
19999,19999,27119,en,The Comic Strip Presents,"['The', 'Comic', 'Strip', 'is', 'a', 'group', ...",['Comedy'],"['surreal', 'parody', 'anthology']","['Rik Mayall', 'Dawn French', 'Adrian Edmondso...",[]

In [31]:
#set_index()
movie_data.set_index("original_language")

,Unnamed: 0,id,title,overview,genre,keywords,cast,crew
original_language,,,,,,,,
en,0,298618,The Flash,"['When', 'his', 'attempt', 'to', 'save', 'his'...","['Action', 'Adventure', 'Science Fiction']","['secret identity', 'hero', 'superhero', 'base...","['Ezra Miller', 'Sasha Calle', 'Michael Keaton...",['Andy Muschietti']
en,1,346698,Barbie,"['Barbie', 'and', 'Ken', 'are', 'having', 'the...","['Comedy', 'Adventure', 'Fantasy']","['feminism', 'patriarchy', 'satire', 'based on...","['Margot Robbie', 'Ryan Gosling', 'Issa Rae', ...",['Greta Gerwig']
en,2,667538,Transformers: Rise of the Beasts,"['When', 'a', 'new', 'threat', 'capable', 'of'...","['Action', 'Adventure', 'Science Fiction']","['peru', 'alien', 'end of the world', 'based o...","['Anthony Ramos', 'Dominique Fishback', 'Peter...",['Steven Caple Jr.']
en,3,385687,Fast X,"['Over', 'many', 'missions', 'and', 'against',...","['Action', 'Crime', 'Thriller']","['sequel', 'revenge', 'racing', 'family', 'cars']","['Vin Diesel', 'Michelle Rodriguez', 'Tyrese G...",['Louis Leterrier']
en,4,872585,Oppenheimer,"['The', 'story', 'of', 'J.', 'Robert', 'Oppenh...","['Drama', 'History']","['based on novel or book', 'husband wife relat...","['Cillian Murphy', 'Emily Blunt', 'Matt Damon'...",['Christopher Nolan']
...,...,...,...,...,...,...,...,...
en,19995,610,Mr. Show with Bob and David,"['Mr.', 'Show', 'with', 'Bob', 'and', 'David',...",['Comedy'],"['drugs', 'sketch comedy', 'dorky']","['Bob Odenkirk', 'David Cross', 'Jill Talley',...",[]
zh,19996,103578,The Twin Flower Legend,"['Hua', 'Mujin', 'grew', 'up', 'during', 'the'...",['Drama'],"['friendship', 'based on novel or book', 'roma...","['Kai Xuan', 'Mao Xiaohui', 'Jim Yu', 'Kenny K...",['Wu Jin Yuan']
zh,19997,72092,Xuan-Yuan Sword: Han Cloud,"['After', 'the', 'ancient', 'Emperor', 'defeat...",['Drama'],"['china', 'romance', 'based on video game', 'x...","['Leon Zhang', 'Alan Yu Menglong', 'Guan Xiaot...","['반문걸', 'Sha Jin', 'Poon Man-kit']"
en,19998,23600,This Is Love,[],[],[],"['Choi Kang-hee', 'Kim Ja-ok', 'Lee Yu-ri']",[]
en,19999,27119,The Comic Strip Presents,"['The', 'Comic', 'Strip', 'is', 'a', 'group', ...",['Comedy'],"['surreal', 'parody', 'anthology']","['Rik Mayall', 'Dawn French', 'Adrian Edmondso...",[]

## Conditional Statements

In [32]:
movie_data.original_language == "en"

0         True
1         True
2         True
3         True
4         True
         ...
19995     True
19996    False
19997    False
19998     True
19999     True
Name: original_language, Length: 20000, dtype: bool

In [33]:
#how to use conditional statement
movie_data.loc[movie_data.original_language == "en"]

,Unnamed: 0,id,original_language,title,overview,genre,keywords,cast,crew
0,0,298618,en,The Flash,"['When', 'his', 'attempt', 'to', 'save', 'his'...","['Action', 'Adventure', 'Science Fiction']","['secret identity', 'hero', 'superhero', 'base...","['Ezra Miller', 'Sasha Calle', 'Michael Keaton...",['Andy Muschietti']
1,1,346698,en,Barbie,"['Barbie', 'and', 'Ken', 'are', 'having', 'the...","['Comedy', 'Adventure', 'Fantasy']","['feminism', 'patriarchy', 'satire', 'based on...","['Margot Robbie', 'Ryan Gosling', 'Issa Rae', ...",['Greta Gerwig']
2,2,667538,en,Transformers: Rise of the Beasts,"['When', 'a', 'new', 'threat', 'capable', 'of'...","['Action', 'Adventure', 'Science Fiction']","['peru', 'alien', 'end of the world', 'based o...","['Anthony Ramos', 'Dominique Fishback', 'Peter...",['Steven Caple Jr.']
3,3,385687,en,Fast X,"['Over', 'many', 'missions', 'and', 'against',...","['Action', 'Crime', 'Thriller']","['sequel', 'revenge', 'racing', 'family', 'cars']","['Vin Diesel', 'Michelle Rodriguez', 'Tyrese G...",['Louis Leterrier']
4,4,872585,en,Oppenheimer,"['The', 'story', 'of', 'J.', 'Robert', 'Oppenh...","['Drama', 'History']","['based on novel or book', 'husband wife relat...","['Cillian Murphy', 'Emily Blunt', 'Matt Damon'...",['Christopher Nolan']
...,...,...,...,...,...,...,...,...,...
19988,19988,102725,en,Taffy,"['The', 'series', 'follows', 'a', 'grey', 'rac...","['Comedy', 'Animation']",[],"['Billy Bob Thompson', 'Tyler Bunch', 'Serra H...",['Ahmed Guerrouache']
19992,19992,3212,en,GamesMaster,"['GamesMaster', 'was', 'a', 'British', 'televi...",[],['video game'],"['Patrick Moore', 'Dominik Diamond']",[]
19995,19995,610,en,Mr. Show with Bob and David,"['Mr.', 'Show', 'with', 'Bob', 'and', 'David',...",['Comedy'],"['drugs', 'sketch comedy', 'dorky']","['Bob Odenkirk', 'David Cross', 'Jill Talley',...",[]
19998,19998,23600,en,This Is Love,[],[],[],"['Choi Kang-hee', 'Kim Ja-ok', 'Lee Yu-ri']",[]
19999,19999,27119,en,The Comic Strip Presents,"['The', 'Comic', 'Strip', 'is', 'a', 'group', ...",['Comedy'],"['surreal', 'parody', 'anthology']","['Rik Mayall', 'Dawn French', 'Adrian Edmondso...",[]

In [38]:
movie_data.loc[(movie_data.original_language == "en") & (movie_data.crew == "['Christopher Nolan']")]

,Unnamed: 0,id,original_language,title,overview,genre,keywords,cast,crew
4,4,872585,en,Oppenheimer,"['The', 'story', 'of', 'J.', 'Robert', 'Oppenh...","['Drama', 'History']","['based on novel or book', 'husband wife relat...","['Cillian Murphy', 'Emily Blunt', 'Matt Damon'...",['Christopher Nolan']
42,42,27205,en,Inception,"['Cobb,', 'a', 'skilled', 'thief', 'who', 'com...","['Action', 'Science Fiction', 'Adventure']","['paris, france', 'spy', 'philosophy', 'allego...","['Leonardo DiCaprio', 'Joseph Gordon-Levitt', ...",['Christopher Nolan']
45,45,157336,en,Interstellar,"['The', 'adventures', 'of', 'a', 'group', 'of'...","['Adventure', 'Drama', 'Science Fiction']","['artificial intelligence', 'nasa', 'time warp...","['Matthew McConaughey', 'Anne Hathaway', 'Jess...",['Christopher Nolan']
71,71,155,en,The Dark Knight,"['Batman', 'raises', 'the', 'stakes', 'in', 'h...","['Drama', 'Action', 'Crime', 'Thriller']","['crime fighter', 'secret identity', 'anti her...","['Christian Bale', 'Heath Ledger', 'Michael Ca...",['Christopher Nolan']
110,110,577922,en,Tenet,"['Armed', 'with', 'only', 'one', 'word', '-', ...","['Action', 'Thriller', 'Science Fiction']","['spy', 'assassin', 'mumbai (bombay), india', ...","['John David Washington', 'Robert Pattinson', ...",['Christopher Nolan']
120,120,49026,en,The Dark Knight Rises,"['Following', 'the', 'death', 'of', 'District'...","['Action', 'Crime', 'Drama', 'Thriller']","['crime fighter', 'terrorist', 'secret identit...","['Christian Bale', 'Michael Caine', 'Gary Oldm...",['Christopher Nolan']
165,165,272,en,Batman Begins,"['Driven', 'by', 'tragedy,', 'billionaire', 'B...","['Action', 'Crime', 'Drama']","['loss of loved one', 'martial arts', 'crime f...","['Christian Bale', 'Liam Neeson', 'Katie Holme...",['Christopher Nolan']
230,230,374720,en,Dunkirk,"['The', 'story', 'of', 'the', 'miraculous', 'e...","['War', 'Action', 'Drama']","['france', 'beach', 'europe', 'world war ii', ...","['Fionn Whitehead', 'Tom Hardy', 'Mark Rylance...",['Christopher Nolan']
278,278,77,en,Memento,"['Leonard', 'Shelby', 'is', 'tracking', 'down'...","['Mystery', 'Thriller']","['insulin', 'tattoo', 'waitress', 'amnesia', '...","['Guy Pearce', 'Carrie-Anne Moss', 'Joe Pantol...",['Christopher Nolan']
528,528,320,en,Insomnia,"['Two', 'Los', 'Angeles', 'homicide', 'detecti...","['Crime', 'Mystery', 'Thriller']","['hotel', 'detective', 'confession', 'small to...","['Al Pacino', 'Robin Williams', 'Hilary Swank'...",['Christopher Nolan']

In [39]:
movie_data.loc[(movie_data.original_language == "en") | (movie_data.crew == "['Christopher Nolan']")]

,Unnamed: 0,id,original_language,title,overview,genre,keywords,cast,crew
0,0,298618,en,The Flash,"['When', 'his', 'attempt', 'to', 'save', 'his'...","['Action', 'Adventure', 'Science Fiction']","['secret identity', 'hero', 'superhero', 'base...","['Ezra Miller', 'Sasha Calle', 'Michael Keaton...",['Andy Muschietti']
1,1,346698,en,Barbie,"['Barbie', 'and', 'Ken', 'are', 'having', 'the...","['Comedy', 'Adventure', 'Fantasy']","['feminism', 'patriarchy', 'satire', 'based on...","['Margot Robbie', 'Ryan Gosling', 'Issa Rae', ...",['Greta Gerwig']
2,2,667538,en,Transformers: Rise of the Beasts,"['When', 'a', 'new', 'threat', 'capable', 'of'...","['Action', 'Adventure', 'Science Fiction']","['peru', 'alien', 'end of the world', 'based o...","['Anthony Ramos', 'Dominique Fishback', 'Peter...",['Steven Caple Jr.']
3,3,385687,en,Fast X,"['Over', 'many', 'missions', 'and', 'against',...","['Action', 'Crime', 'Thriller']","['sequel', 'revenge', 'racing', 'family', 'cars']","['Vin Diesel', 'Michelle Rodriguez', 'Tyrese G...",['Louis Leterrier']
4,4,872585,en,Oppenheimer,"['The', 'story', 'of', 'J.', 'Robert', 'Oppenh...","['Drama', 'History']","['based on novel or book', 'husband wife relat...","['Cillian Murphy', 'Emily Blunt', 'Matt Damon'...",['Christopher Nolan']
...,...,...,...,...,...,...,...,...,...
19988,19988,102725,en,Taffy,"['The', 'series', 'follows', 'a', 'grey', 'rac...","['Comedy', 'Animation']",[],"['Billy Bob Thompson', 'Tyler Bunch', 'Serra H...",['Ahmed Guerrouache']
19992,19992,3212,en,GamesMaster,"['GamesMaster', 'was', 'a', 'British', 'televi...",[],['video game'],"['Patrick Moore', 'Dominik Diamond']",[]
19995,19995,610,en,Mr. Show with Bob and David,"['Mr.', 'Show', 'with', 'Bob', 'and', 'David',...",['Comedy'],"['drugs', 'sketch comedy', 'dorky']","['Bob Odenkirk', 'David Cross', 'Jill Talley',...",[]
19998,19998,23600,en,This Is Love,[],[],[],"['Choi Kang-hee', 'Kim Ja-ok', 'Lee Yu-ri']",[]
19999,19999,27119,en,The Comic Strip Presents,"['The', 'Comic', 'Strip', 'is', 'a', 'group', ...",['Comedy'],"['surreal', 'parody', 'anthology']","['Rik Mayall', 'Dawn French', 'Adrian Edmondso...",[]

In [40]:
#isin
movie_data.loc[movie_data.original_language.isin(["zh", "hi"])]

,Unnamed: 0,id,original_language,title,overview,genre,keywords,cast,crew
369,369,870096,zh,Restart the Earth,"['When', 'a', 'drug', 'to', 'replicate', 'plan...","['Science Fiction', 'Horror', 'Action']","['dangerous mission', 'environmental disaster'...","['He Shengming', 'Mi Luo', 'Michelle Ye', 'Yu ...",['Lin Zhenzhao']
390,390,20453,hi,3 Idiots,"['Rascal.', 'Joker.', 'Dreamer.', 'Genius...',...","['Drama', 'Comedy']","['suicide', 'suicide attempt', 'college', 'mus...","['Aamir Khan', 'R. Madhavan', 'Sharman Joshi',...",['Rajkumar Hirani']
423,423,19404,hi,Dilwale Dulhania Le Jayenge,"['Raj', 'is', 'a', 'rich,', 'carefree,', 'happ...","['Comedy', 'Drama', 'Romance']","[""family's daily life"", 'family history', 'lov...","['Shah Rukh Khan', 'Kajol', 'Amrish Puri', 'An...",['Aditya Chopra']
440,440,1136736,hi,Lust Stories 2,"['Four', 'eminent', 'Indian', 'directors', 'ex...","['Drama', 'Romance']","['love', 'anthology', 'lust']","['Neena Gupta', 'Mrunal Thakur', 'Tamannaah Bh...","['Konkona Sen Sharma', 'R. Balki', 'Sujoy Ghos..."
514,514,783461,hi,Looop Lapeta,"['When', 'her', 'boyfriend', 'loses', 'a', ""mo...","['Action', 'Comedy', 'Crime']","['remake', 'looop lapeta', 'saade saati']","['Taapsee Pannu', 'Tahir Raj Bhasin', 'Shreya ...",['Aakash Bhatia']
...,...,...,...,...,...,...,...,...,...
19951,19951,109331,zh,The Promise of Chang’An,"['he', 'story', 'is', 'set', 'in', 'the', 'fic...",['Drama'],"['romance', 'sibling rivalry', 'historical', '...","['Zhao Yingzi', 'Cheng Yi', 'Han Dong', 'Vicky...",['Yin Tao']
19969,19969,122413,zh,中国传统动画精粹合集,[],[],[],[],[]
19979,19979,63217,zh,Tiny Times,"['Based', 'on', 'the', 'best-selling', 'novels...",['Drama'],"['china', 'university', 'fashion magazine', 'c...","['Ivy Chen', 'Jiang Kaitong', 'Andrea Chen', '...",['Qu Youning']
19996,19996,103578,zh,The Twin Flower Legend,"['Hua', 'Mujin', 'grew', 'up', 'during', 'the'...",['Drama'],"['friendship', 'based on novel or book', 'roma...","['Kai Xuan', 'Mao Xiaohui', 'Jim Yu', 'Kenny K...",['Wu Jin Yuan']
19997,19997,72092,zh,Xuan-Yuan Sword: Han Cloud,"['After', 'the', 'ancient', 'Emperor', 'defeat...",['Drama'],"['china', 'romance', 'based on video game', 'x...","['Leon Zhang', 'Alan Yu Menglong', 'Guan Xiaot...","['반문걸', 'Sha Jin', 'Poon Man-kit']"

In [43]:
movie_data.loc[movie_data.overview.notnull()]

,Unnamed: 0,id,original_language,title,overview,genre,keywords,cast,crew
0,0,298618,en,The Flash,"['When', 'his', 'attempt', 'to', 'save', 'his'...","['Action', 'Adventure', 'Science Fiction']","['secret identity', 'hero', 'superhero', 'base...","['Ezra Miller', 'Sasha Calle', 'Michael Keaton...",['Andy Muschietti']
1,1,346698,en,Barbie,"['Barbie', 'and', 'Ken', 'are', 'having', 'the...","['Comedy', 'Adventure', 'Fantasy']","['feminism', 'patriarchy', 'satire', 'based on...","['Margot Robbie', 'Ryan Gosling', 'Issa Rae', ...",['Greta Gerwig']
2,2,667538,en,Transformers: Rise of the Beasts,"['When', 'a', 'new', 'threat', 'capable', 'of'...","['Action', 'Adventure', 'Science Fiction']","['peru', 'alien', 'end of the world', 'based o...","['Anthony Ramos', 'Dominique Fishback', 'Peter...",['Steven Caple Jr.']
3,3,385687,en,Fast X,"['Over', 'many', 'missions', 'and', 'against',...","['Action', 'Crime', 'Thriller']","['sequel', 'revenge', 'racing', 'family', 'cars']","['Vin Diesel', 'Michelle Rodriguez', 'Tyrese G...",['Louis Leterrier']
4,4,872585,en,Oppenheimer,"['The', 'story', 'of', 'J.', 'Robert', 'Oppenh...","['Drama', 'History']","['based on novel or book', 'husband wife relat...","['Cillian Murphy', 'Emily Blunt', 'Matt Damon'...",['Christopher Nolan']
...,...,...,...,...,...,...,...,...,...
19995,19995,610,en,Mr. Show with Bob and David,"['Mr.', 'Show', 'with', 'Bob', 'and', 'David',...",['Comedy'],"['drugs', 'sketch comedy', 'dorky']","['Bob Odenkirk', 'David Cross', 'Jill Talley',...",[]
19996,19996,103578,zh,The Twin Flower Legend,"['Hua', 'Mujin', 'grew', 'up', 'during', 'the'...",['Drama'],"['friendship', 'based on novel or book', 'roma...","['Kai Xuan', 'Mao Xiaohui', 'Jim Yu', 'Kenny K...",['Wu Jin Yuan']
19997,19997,72092,zh,Xuan-Yuan Sword: Han Cloud,"['After', 'the', 'ancient', 'Emperor', 'defeat...",['Drama'],"['china', 'romance', 'based on video game', 'x...","['Leon Zhang', 'Alan Yu Menglong', 'Guan Xiaot...","['반문걸', 'Sha Jin', 'Poon Man-kit']"
19998,19998,23600,en,This Is Love,[],[],[],"['Choi Kang-hee', 'Kim Ja-ok', 'Lee Yu-ri']",[]
19999,19999,27119,en,The Comic Strip Presents,"['The', 'Comic', 'Strip', 'is', 'a', 'group', ...",['Comedy'],"['surreal', 'parody', 'anthology']","['Rik Mayall', 'Dawn French', 'Adrian Edmondso...",[]

In [44]:
movie_data.loc[movie_data.overview.isnull()]

Empty DataFrame
Columns: [Unnamed: 0, id, original_language, title, overview, genre, keywords, cast, crew]
Index: []

## Summary or Mapping data

In [46]:
movie_data.original_language.describe()

count     20000
unique       68
top          en
freq       5712
Name: original_language, dtype: object

In [47]:
movie_data.original_language.unique()

array(['en', 'ja', 'es', 'pl', 'no', 'it', 'ko', 'te', 'fr', 'zh', 'pt',
       'hi', 'ta', 'id', 'kn', 'ru', 'th', 'cn', 'ml', 'da', 'ar', 'de',
       'bn', 'sr', 'nl', 'sv', 'pa', 'fi', 'fa', 'ca', 'gu', 'et', 'tr',
       'uk', 'mr', 'or', 'am', 'ur', 'bg', 'hu', 'as', 'ku', 'xx', 'az',
       'cs', 'ne', 'ky', 'sa', 'ks', 'el', 'tl', 'ms', 'sk', 'he', 'cy',
       'vi', 'is', 'ro', 'ka', 'la', 'bs', 'gl', 'lb', 'ab', 'zu', 'sl',
       'af', 'lt'], dtype=object)

In [48]:
movie_data.original_language.value_counts()

original_language
en    5712
hi    2990
ta    1972
ja    1901
ml    1535
      ...
ks       1
ky       1
ne       1
am       1
lt       1
Name: count, Length: 68, dtype: int64

In [49]:
movie_data.head()

,Unnamed: 0,id,original_language,title,overview,genre,keywords,cast,crew
0,0,298618,en,The Flash,"['When', 'his', 'attempt', 'to', 'save', 'his'...","['Action', 'Adventure', 'Science Fiction']","['secret identity', 'hero', 'superhero', 'base...","['Ezra Miller', 'Sasha Calle', 'Michael Keaton...",['Andy Muschietti']
1,1,346698,en,Barbie,"['Barbie', 'and', 'Ken', 'are', 'having', 'the...","['Comedy', 'Adventure', 'Fantasy']","['feminism', 'patriarchy', 'satire', 'based on...","['Margot Robbie', 'Ryan Gosling', 'Issa Rae', ...",['Greta Gerwig']
2,2,667538,en,Transformers: Rise of the Beasts,"['When', 'a', 'new', 'threat', 'capable', 'of'...","['Action', 'Adventure', 'Science Fiction']","['peru', 'alien', 'end of the world', 'based o...","['Anthony Ramos', 'Dominique Fishback', 'Peter...",['Steven Caple Jr.']
3,3,385687,en,Fast X,"['Over', 'many', 'missions', 'and', 'against',...","['Action', 'Crime', 'Thriller']","['sequel', 'revenge', 'racing', 'family', 'cars']","['Vin Diesel', 'Michelle Rodriguez', 'Tyrese G...",['Louis Leterrier']
4,4,872585,en,Oppenheimer,"['The', 'story', 'of', 'J.', 'Robert', 'Oppenh...","['Drama', 'History']","['based on novel or book', 'husband wife relat...","['Cillian Murphy', 'Emily Blunt', 'Matt Damon'...",['Christopher Nolan']

## Grouping and Sorting

In [52]:
movie_data.groupby("original_language").title.count()

original_language
ab      2
af      1
am      1
ar     30
as      7
     ...
ur      9
vi      5
xx      6
zh    615
zu      1
Name: title, Length: 68, dtype: int64

## Renaming the columns

In [53]:
movie_data.rename(columns={"original_language":"language"})

,Unnamed: 0,id,language,title,overview,genre,keywords,cast,crew
0,0,298618,en,The Flash,"['When', 'his', 'attempt', 'to', 'save', 'his'...","['Action', 'Adventure', 'Science Fiction']","['secret identity', 'hero', 'superhero', 'base...","['Ezra Miller', 'Sasha Calle', 'Michael Keaton...",['Andy Muschietti']
1,1,346698,en,Barbie,"['Barbie', 'and', 'Ken', 'are', 'having', 'the...","['Comedy', 'Adventure', 'Fantasy']","['feminism', 'patriarchy', 'satire', 'based on...","['Margot Robbie', 'Ryan Gosling', 'Issa Rae', ...",['Greta Gerwig']
2,2,667538,en,Transformers: Rise of the Beasts,"['When', 'a', 'new', 'threat', 'capable', 'of'...","['Action', 'Adventure', 'Science Fiction']","['peru', 'alien', 'end of the world', 'based o...","['Anthony Ramos', 'Dominique Fishback', 'Peter...",['Steven Caple Jr.']
3,3,385687,en,Fast X,"['Over', 'many', 'missions', 'and', 'against',...","['Action', 'Crime', 'Thriller']","['sequel', 'revenge', 'racing', 'family', 'cars']","['Vin Diesel', 'Michelle Rodriguez', 'Tyrese G...",['Louis Leterrier']
4,4,872585,en,Oppenheimer,"['The', 'story', 'of', 'J.', 'Robert', 'Oppenh...","['Drama', 'History']","['based on novel or book', 'husband wife relat...","['Cillian Murphy', 'Emily Blunt', 'Matt Damon'...",['Christopher Nolan']
...,...,...,...,...,...,...,...,...,...
19995,19995,610,en,Mr. Show with Bob and David,"['Mr.', 'Show', 'with', 'Bob', 'and', 'David',...",['Comedy'],"['drugs', 'sketch comedy', 'dorky']","['Bob Odenkirk', 'David Cross', 'Jill Talley',...",[]
19996,19996,103578,zh,The Twin Flower Legend,"['Hua', 'Mujin', 'grew', 'up', 'during', 'the'...",['Drama'],"['friendship', 'based on novel or book', 'roma...","['Kai Xuan', 'Mao Xiaohui', 'Jim Yu', 'Kenny K...",['Wu Jin Yuan']
19997,19997,72092,zh,Xuan-Yuan Sword: Han Cloud,"['After', 'the', 'ancient', 'Emperor', 'defeat...",['Drama'],"['china', 'romance', 'based on video game', 'x...","['Leon Zhang', 'Alan Yu Menglong', 'Guan Xiaot...","['반문걸', 'Sha Jin', 'Poon Man-kit']"
19998,19998,23600,en,This Is Love,[],[],[],"['Choi Kang-hee', 'Kim Ja-ok', 'Lee Yu-ri']",[]
19999,19999,27119,en,The Comic Strip Presents,"['The', 'Comic', 'Strip', 'is', 'a', 'group', ...",['Comedy'],"['surreal', 'parody', 'anthology']","['Rik Mayall', 'Dawn French', 'Adrian Edmondso...",[]

In [54]:
movie_data.rename(columns={"title":"Movie Title"})

,Unnamed: 0,id,original_language,Movie Title,overview,genre,keywords,cast,crew
0,0,298618,en,The Flash,"['When', 'his', 'attempt', 'to', 'save', 'his'...","['Action', 'Adventure', 'Science Fiction']","['secret identity', 'hero', 'superhero', 'base...","['Ezra Miller', 'Sasha Calle', 'Michael Keaton...",['Andy Muschietti']
1,1,346698,en,Barbie,"['Barbie', 'and', 'Ken', 'are', 'having', 'the...","['Comedy', 'Adventure', 'Fantasy']","['feminism', 'patriarchy', 'satire', 'based on...","['Margot Robbie', 'Ryan Gosling', 'Issa Rae', ...",['Greta Gerwig']
2,2,667538,en,Transformers: Rise of the Beasts,"['When', 'a', 'new', 'threat', 'capable', 'of'...","['Action', 'Adventure', 'Science Fiction']","['peru', 'alien', 'end of the world', 'based o...","['Anthony Ramos', 'Dominique Fishback', 'Peter...",['Steven Caple Jr.']
3,3,385687,en,Fast X,"['Over', 'many', 'missions', 'and', 'against',...","['Action', 'Crime', 'Thriller']","['sequel', 'revenge', 'racing', 'family', 'cars']","['Vin Diesel', 'Michelle Rodriguez', 'Tyrese G...",['Louis Leterrier']
4,4,872585,en,Oppenheimer,"['The', 'story', 'of', 'J.', 'Robert', 'Oppenh...","['Drama', 'History']","['based on novel or book', 'husband wife relat...","['Cillian Murphy', 'Emily Blunt', 'Matt Damon'...",['Christopher Nolan']
...,...,...,...,...,...,...,...,...,...
19995,19995,610,en,Mr. Show with Bob and David,"['Mr.', 'Show', 'with', 'Bob', 'and', 'David',...",['Comedy'],"['drugs', 'sketch comedy', 'dorky']","['Bob Odenkirk', 'David Cross', 'Jill Talley',...",[]
19996,19996,103578,zh,The Twin Flower Legend,"['Hua', 'Mujin', 'grew', 'up', 'during', 'the'...",['Drama'],"['friendship', 'based on novel or book', 'roma...","['Kai Xuan', 'Mao Xiaohui', 'Jim Yu', 'Kenny K...",['Wu Jin Yuan']
19997,19997,72092,zh,Xuan-Yuan Sword: Han Cloud,"['After', 'the', 'ancient', 'Emperor', 'defeat...",['Drama'],"['china', 'romance', 'based on video game', 'x...","['Leon Zhang', 'Alan Yu Menglong', 'Guan Xiaot...","['반문걸', 'Sha Jin', 'Poon Man-kit']"
19998,19998,23600,en,This Is Love,[],[],[],"['Choi Kang-hee', 'Kim Ja-ok', 'Lee Yu-ri']",[]
19999,19999,27119,en,The Comic Strip Presents,"['The', 'Comic', 'Strip', 'is', 'a', 'group', ...",['Comedy'],"['surreal', 'parody', 'anthology']","['Rik Mayall', 'Dawn French', 'Adrian Edmondso...",[]

## Tasks to Complete
### Concatenate multiple datasets
### Join()